-- ATOM SERVICE DATABASE DDL, AUTO GENERATED BY TENCENT. DO NOT MODIFY! --

CREATE TABLE IF NOT EXISTS `dict_item_edd9ffd674a960e5`(
	`id` BIGINT AUTO_INCREMENT COMMENT '自增主键',
	`ge_dict_name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '字典类型名称',
	`ge_dict_code` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '字典类型编码',
	PRIMARY KEY(`id`),
	UNIQUE INDEX `unique_idx_ge_dict_name` USING HASH (`ge_dict_name` ASC),
	UNIQUE INDEX `unique_idx_ge_dict_code` USING HASH (`ge_dict_code` ASC)
) ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT '全局数据字典抬头信息';

CREATE TABLE IF NOT EXISTS `dict_item_information_edd9ffd674a960e5`(
	`id` BIGINT AUTO_INCREMENT COMMENT '自增主键',
	`state` BIGINT COMMENT '状态（0:启用，-1:停用）',
	`ge_dict_code` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '字典类型编码',
	`ge_dict_info_decs` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字典描述',
	`ge_dict_info_code` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '字典编码',
	PRIMARY KEY(`id`),
	UNIQUE INDEX `unique_idx_state` USING HASH (`state` ASC),
	UNIQUE INDEX `unique_idx_ge_dict_info_decs` USING HASH (`ge_dict_info_decs` ASC),
	UNIQUE INDEX `unique_idx_ge_dict_info_code` USING HASH (`ge_dict_info_code` ASC)
) ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT '全局数据字典明细';

CREATE TABLE IF NOT EXISTS `addd_edd9ffd674a960e5`(
	`id` BIGINT AUTO_INCREMENT COMMENT '自增主键',
	`namedd` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '撒打算的',
	`test` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'ttt',
	PRIMARY KEY(`id`),
	INDEX `idx_namedd` USING BTREE (`namedd` ASC)
) ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT '撒打算';

